name: aivandb
run-name: Setting up the Aivan database
on: [push]
jobs:
  test-output:
    runs-on: ubuntu-latest
    steps:
    - name: Test Output
      run: echo "Here is a test"
  connect-remote:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Show databases
      run: mysql -h ${{ vars.DB_HOSTNAME }} --port ${{ vars.DB_PORT }}  -u${{ secrets.DB_USER }} -p${{ secrets.DB_PASSWORD }} -e "SHOW DATABASES";
    - name: Run a sample SQL on remote
      run: mysql -h ${{ vars.DB_HOSTNAME }} --port ${{ vars.DB_PORT }} -u${{ secrets.DB_USER }} -p${{ secrets.DB_PASSWORD }} -e "source Database/testingDB.sql" trailnetdb;
